# Generated by Django 5.1.6 on 2025-03-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executionrequest',
            name='sandbox',
        ),
    ]
