# Generated by Django 5.1.6 on 2025-03-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0002_remove_executionrequest_sandbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionrequest',
            name='sandbox',
            field=models.CharField(default='piston', max_length=50),
        ),
    ]
