# Generated by Django 5.1.6 on 2025-03-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0003_executionrequest_sandbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionrequest',
            name='stdin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
