# Generated by Django 5.1.6 on 2025-03-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0004_executionrequest_stdin'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionrequest',
            name='args',
            field=models.TextField(blank=True, null=True),
        ),
    ]
