# Generated by Django 5.1.6 on 2025-03-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0006_executionresult_test_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionresult',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
