# Generated by Django 5.1.6 on 2025-04-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_alter_badge_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='requirements',
            field=models.TextField(blank=True),
        ),
    ]
