# Generated by Django 5.1.6 on 2025-03-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_exercise_created_by_lesson_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='sandbox',
            field=models.CharField(default='piston', max_length=50),
        ),
    ]
